#!/usr/bin/env python3
"""Regenerate the reviews wall in index.html from reviews.json.

Usage:  python tools/build-reviews.py

Reads reviews.json, renders one card per review, splits them across two
rows (row 1 scrolls left, row 2 scrolls right) and writes the result
between the REVIEWS:START / REVIEWS:END markers in index.html.

Each row's cards are emitted TWICE. The marquee animates the track from
0 to -50%, so the second copy is what makes the loop seamless — and the
per-card spacing has to be margin-right rather than flex gap, otherwise
-50% lands mid-gap and the join visibly jumps.
"""

import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "reviews.json")
PAGE = os.path.join(ROOT, "index.html")
START = "    <!-- REVIEWS:START — generated by tools/build-reviews.py, do not edit by hand -->"
END = "    <!-- REVIEWS:END -->"


def initials(name, override=None):
    if override:
        return override
    parts = [p for p in re.split(r"\s+", name.strip()) if p]
    if not parts:
        return "?"
    if len(parts) == 1:
        return parts[0][:2].upper()
    return (parts[0][0] + parts[-1][0]).upper()


def avatar_html(r):
    if r.get("avatar"):
        return (
            '<span class="cp-rw__face" style="background: url({src}) center / cover no-repeat;" '
            'role="img" aria-label="{name}"></span>'
        ).format(src=html.escape(r["avatar"], quote=True), name=html.escape(r["name"], quote=True))
    return '<span class="cp-rw__face cp-rw__face--txt" aria-hidden="true">{ini}</span>'.format(
        ini=html.escape(initials(r["name"], r.get("initials")))
    )


def logo_html(r):
    if not r.get("logo"):
        return ""
    return '<img class="cp-rw__logo" src="{src}" alt="{alt}">'.format(
        src=html.escape(r["logo"], quote=True),
        alt=html.escape(r.get("logoAlt", ""), quote=True),
    )


QUOTE_OPEN = (
    '<svg class="cp-rw__q" width="26" height="20" viewBox="0 0 26 20" fill="#252525" aria-hidden="true">'
    '<path d="M0 20V11.6C0 5.6 3.4 1.2 9.6 0l1.2 3.2C7 4.4 5.2 6.6 5.2 9.2h4.2V20H0Z'
    'm14.8 0V11.6C14.8 5.6 18.2 1.2 24.4 0L25.6 3.2c-3.8 1.2-5.6 3.4-5.6 6h4.2V20h-9.4Z"/></svg>'
)
QUOTE_CLOSE = (
    '<svg class="cp-rw__q cp-rw__q--end" width="22" height="17" viewBox="0 0 26 20" fill="#252525" aria-hidden="true">'
    '<path d="M26 0v8.4c0 6-3.4 10.4-9.6 11.6l-1.2-3.2c3.8-1.2 5.6-3.4 5.6-6h-4.2V0H26Z'
    'M11.2 0v8.4c0 6-3.4 10.4-9.6 11.6L.4 16.8c3.8-1.2 5.6-3.4 5.6-6H1.8V0h9.4Z"/></svg>'
)


def card(r):
    return (
        '        <figure class="cp-rw__card">\n'
        "          {qopen}\n"
        '          <blockquote class="cp-rw__text">{quote}</blockquote>\n'
        "          {qclose}\n"
        '          <figcaption class="cp-rw__foot">\n'
        '            <span class="cp-rw__who">{avatar}<span class="cp-rw__id">'
        '<span class="cp-rw__name">{name}</span>'
        '<span class="cp-rw__role">{role}</span></span></span>\n'
        "            {logo}\n"
        "          </figcaption>\n"
        "        </figure>"
    ).format(
        qopen=QUOTE_OPEN,
        qclose=QUOTE_CLOSE,
        quote=html.escape(r["quote"]),
        name=html.escape(r["name"]),
        role=html.escape(r.get("role") or r.get("date") or ""),
        avatar=avatar_html(r),
        logo=logo_html(r),
    )


def row(reviews, direction):
    cards = "\n".join(card(r) for r in reviews)
    # emitted twice — the second set is the seamless wrap-around
    return (
        '      <div class="cp-rw__track cp-rw__track--{d}">\n{cards}\n{cards}\n      </div>'
    ).format(d=direction, cards=cards)


def main():
    with open(DATA, encoding="utf-8") as fh:
        reviews = json.load(fh)["reviews"]

    if not reviews:
        sys.exit("reviews.json has no entries")

    # alternate so both rows stay balanced however many reviews there are
    top = reviews[0::2]
    bottom = reviews[1::2] or top

    block = "\n".join([
        START,
        '    <div class="cp-rw">',
        row(top, "left"),
        "    </div>",
        '    <div class="cp-rw">',
        row(bottom, "right"),
        "    </div>",
        END,
    ])

    with open(PAGE, encoding="utf-8", newline="") as fh:
        page = fh.read()

    nl = "\r\n" if "\r\n" in page else "\n"
    if START not in page or END not in page:
        sys.exit("markers not found in index.html — add REVIEWS:START/END first")

    i = page.index(START)
    j = page.index(END) + len(END)
    page = page[:i] + block.replace("\n", nl) + page[j:]

    with open(PAGE, "w", encoding="utf-8", newline="") as fh:
        fh.write(page)

    print("wrote %d reviews — %d in the top row, %d in the bottom" % (len(reviews), len(top), len(bottom)))


if __name__ == "__main__":
    main()
