#!/usr/bin/env python3
"""Render the case-study ring from brands.json into index.html.

Usage:  python tools/build-case-studies.py

Writes the cards between the CASESTUDIES markers. One card per brand,
each carrying the logo, the tier where there is one, the merchant's own
words and where they trade.

The ring's geometry lives here rather than in CSS because each card needs
its own angle: card i sits at i * 360/n degrees and is pushed out by the
radius, which is derived from the card pitch so the cards never overlap
however many brands the file holds.
"""

import html
import io
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "brands.json")
PAGE = os.path.join(ROOT, "index.html")
LOGOS = "assets/customers"
START = "      <!-- CASESTUDIES:START — generated by tools/build-case-studies.py -->"
END = "      <!-- CASESTUDIES:END -->"

CARD_W = 246
PITCH = 268          # centre-to-centre along the circle


PLAY = ('<svg width="18" height="21" viewBox="0 0 30 34" fill="currentColor" '
        'aria-hidden="true"><path d="M28.5 15.3a2 2 0 0 1 0 3.4L3.1 33.6A2 2 0 '
        '0 1 0 31.9V2.1A2 2 0 0 1 3.1.4z"></path></svg>')


def video_card(v, angle, radius):
    """One card in the ring is a merchant on camera rather than in print.

    The poster fills the card edge to edge and the line sits over it, so it
    reads as a different kind of evidence at a glance. The click binding is
    the page's own playVT0, which also holds the ring still while it plays -
    a card that turns away mid-sentence is worse than no card.
    """
    return [
        '          <figure class="cp-cs__card cp-cs__card--vt" id="cp-vt-0" '
        'data-playing="0" data-cs-angle="%.3f" '
        'style="transform: rotateY(%.3fdeg) translateZ(%dpx);">'
        % (angle, angle, radius),
        '            <video class="cp-vt__video" preload="none" playsinline '
        'poster="%s" width="%d" height="%d">'
        % (v["poster"], v["width"], v["height"]),
        '              <source src="%s" type="video/mp4">' % v["src"],
        "            </video>",
        '            <button type="button" class="cp-vt__hit" '
        'onClick="{{ playVT0 }}" aria-label="Play: %s">'
        '<span class="cp-vt__play">%s</span>'
        '<span class="cp-vt__time">%s</span></button>'
        % (html.escape(v["title"].strip("“”"), quote=True), PLAY,
           html.escape(v["duration"])),
        '            <figcaption class="cp-cs__vtcap">%s</figcaption>'
        % html.escape(v["title"]),
        "          </figure>",
    ]


def main():
    doc = json.load(io.open(DATA, encoding="utf-8"))
    brands = doc if isinstance(doc, list) else doc.get("brands", doc)
    n = len(brands)
    # the circle has to be long enough to seat every card at its pitch
    radius = int(round(n * PITCH / (2 * math.pi)))
    step = 360.0 / n

    out = [START,
           '      <div class="cp-cs" data-cs-radius="%d">' % radius,
           '        <div class="cp-cs__ring" id="cp-cs-ring">']
    for i, b in enumerate(brands):
        angle = i * step
        if b.get("video"):
            out += video_card(b["video"], angle, radius)
            continue
        tier = b.get("tier")
        bits = [
            '          <figure class="cp-cs__card" data-cs-angle="%.3f" '
            'style="transform: rotateY(%.3fdeg) translateZ(%dpx);">'
            % (angle, angle, radius),
            '            <span class="cp-cs__mark">'
            '<img src="%s/%s" alt="%s"></span>'
            % (LOGOS, b["file"], html.escape(b["name"], quote=True)),
        ]
        if tier:
            bits.append('            <span class="cp-cs__tier">%s</span>'
                        % html.escape(tier))
        bits += [
            '            <blockquote class="cp-cs__quote">%s</blockquote>'
            % html.escape(b["review"]),
            '            <figcaption class="cp-cs__who">%s%s</figcaption>'
            % (html.escape(b["reviewer"]),
               ('<span class="cp-cs__where">%s</span>' % html.escape(b["country"]))
               if b.get("country") else ""),
            "          </figure>",
        ]
        out += bits
    out += ["        </div>", "      </div>", END]

    block = "\n".join(out)
    s = io.open(PAGE, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in s else "\n"
    if START not in s:
        raise SystemExit("CASESTUDIES markers not found in index.html")
    a = s.index(START)
    b = s.index(END) + len(END)
    s = s[:a] + block.replace("\n", nl) + s[b:]
    io.open(PAGE, "w", encoding="utf-8", newline="").write(s)
    print("wrote %d case-study cards, radius %dpx, %.1f degrees apart"
          % (n, radius, step))


if __name__ == "__main__":
    main()
