#!/usr/bin/env python3
"""Regenerate the Trusted-by brand strip in index.html from brands.json.

Usage:  python tools/build-brand-strip.py

Port of BrandStrip.tsx from the OE demo landing page. That component is
React + Tailwind; this project is static HTML with a dc runtime and no
Tailwind, so the markup is plain and the styling lives in the .cp-bs block
in index.html.

Two behavioural notes, both forced by having no rAF loop to lean on:

  * The original slows to 15% speed on hover. A CSS keyframe can't change
    rate without jumping, so this pauses instead. Same purpose - an
    expanded card holds still while you read it.
  * The track shifts by one set width in PIXELS, not -50%. An expanded
    card widens the track, so a percentage shift would drift. That width
    is derived in CSS from --cp-bs-cell, which is why this only writes
    --cp-bs-count: a breakpoint can then resize the cells and the shift
    still lands on a cell boundary.
"""

import html
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "brands.json")
PAGE = os.path.join(ROOT, "index.html")
LOGO_BASE = "assets/customers"

START = "      <!-- BRANDSTRIP:START — generated by tools/build-brand-strip.py, do not edit by hand -->"
END = "      <!-- BRANDSTRIP:END -->"



def card(b, dupe):
    bits = [
        '        <div class="cp-bs__item"%s>' % (' aria-hidden="true"' if dupe else ""),
        '          <div class="cp-bs__brand">',
        '            <span class="cp-bs__mark"><img src="{base}/{file}" alt="{alt}"></span>'.format(
            base=LOGO_BASE,
            file=html.escape(b["file"], quote=True),
            alt=html.escape(b["name"], quote=True),
        ),
    ]
    if b.get("tier"):
        bits.append('            <span class="cp-bs__tier">%s</span>' % html.escape(b["tier"]))
    bits.append('          </div>')

    if b.get("review"):
        quote = '“%s”' % html.escape(b["review"])
        cls = "cp-bs__quote"
    else:
        quote = "Verified Clickpost customer — review coming soon."
        cls = "cp-bs__quote cp-bs__quote--none"
    bits += [
        '          <div class="cp-bs__panel"><div class="cp-bs__panelin">',
        '            <p class="%s">%s</p>' % (cls, quote),
        '            <div class="cp-bs__who">{name}{where}</div>'.format(
            name=html.escape(b["reviewer"]),
            where=('<span class="cp-bs__where">%s</span>' % html.escape(b["country"])) if b.get("country") else "",
        ),
        '          </div></div>',
        '        </div>',
    ]
    return "\n".join(bits)


def main():
    with io.open(DATA, encoding="utf-8") as fh:
        brands = json.load(fh)["brands"]

    if not brands:
        sys.exit("brands.json has no entries")

    for b in brands:
        path = os.path.join(ROOT, LOGO_BASE, b["file"])
        if not os.path.exists(path):
            sys.exit("missing logo: %s" % path)

    # The stylesheet derives span and half-cell from --cp-bs-cell, so a
    # breakpoint can resize the cells without the loop losing its seam.
    # Only the count is needed here.
    # emitted twice - the second set is what the loop wraps onto
    cards = "\n".join(card(b, False) for b in brands)
    dupes = "\n".join(card(b, True) for b in brands)
    block = "\n".join([
        START,
        '      <div class="cp-bs" style="align-self: stretch;">',
        '        <div class="cp-bs__track" style="--cp-bs-count: %d;">'
        % len(brands),
        cards,
        dupes,
        "        </div>",
        "      </div>",
        END,
    ])

    with io.open(PAGE, encoding="utf-8", newline="") as fh:
        page = fh.read()

    nl = "\r\n" if "\r\n" in page else "\n"
    if START not in page or END not in page:
        sys.exit("markers not found in index.html — add BRANDSTRIP:START/END first")

    i = page.index(START)
    j = page.index(END) + len(END)
    page = page[:i] + block.replace("\n", nl) + page[j:]

    with io.open(PAGE, "w", encoding="utf-8", newline="") as fh:
        fh.write(page)

    print("wrote %d brands (cell width lives in the stylesheet)"
          % len(brands))


if __name__ == "__main__":
    main()
