#!/usr/bin/env python3
"""Bake the globe's land dots into index.html.

Usage:  python tools/build-globe-dots.py

Samples a lon/lat grid against Natural Earth's 110m land polygons and
writes the land points into the page between the GLOBEDOTS markers, as
JSON in a script tag.

Done at build time on purpose. The component this replaces fetched the
same GeoJSON from raw.githubusercontent.com on every page view and ran
point-in-polygon over it in the browser - a third-party request on the
critical path, and roughly 10,000 polygon tests before the first frame.
The result never changes, so it is computed once here. What ships is a
flat list of coordinates the page projects directly.

The GeoJSON is fetched once, by this script, and is not committed - only
its output is.
"""

import io
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "index.html")
SRC = ("https://raw.githubusercontent.com/martynafford/natural-earth-geojson/"
       "master/110m/physical/ne_110m_land.json")
START = "  <!-- GLOBEDOTS:START — generated by tools/build-globe-dots.py -->"
END = "  <!-- GLOBEDOTS:END -->"

STEP = 2.5          # degrees between samples
LAT_TOP = 80.0      # trim the poles: nothing to show, and the dots crowd
LAT_BOTTOM = -58.0  # above Antarctica, which is all coastline and no stores


def ring_contains(x, y, ring):
    inside = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i][0], ring[i][1]
        xj, yj = ring[j][0], ring[j][1]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            inside = not inside
        j = i
    return inside


def polygon_contains(x, y, rings):
    """Outer ring holds it and no inner ring (a lake) cuts it out."""
    if not ring_contains(x, y, rings[0]):
        return False
    for hole in rings[1:]:
        if ring_contains(x, y, hole):
            return False
    return True


def feature_contains(x, y, geom):
    t = geom["type"]
    if t == "Polygon":
        return polygon_contains(x, y, geom["coordinates"])
    if t == "MultiPolygon":
        for rings in geom["coordinates"]:
            if polygon_contains(x, y, rings):
                return True
    return False


def bbox(geom):
    xs, ys = [], []
    parts = ([geom["coordinates"]] if geom["type"] == "Polygon"
             else geom["coordinates"])
    for rings in parts:
        for x, y in rings[0]:
            xs.append(x)
            ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


def main():
    print("fetching %s" % SRC)
    req = urllib.request.Request(SRC, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        land = json.loads(r.read().decode("utf-8"))
    feats = land["features"]
    print("%d land features" % len(feats))

    # a bounding box per feature keeps this to a few seconds instead of
    # testing every point against every polygon
    boxes = [bbox(f["geometry"]) for f in feats]

    dots = []
    lat = LAT_BOTTOM
    while lat <= LAT_TOP:
        lon = -180.0
        while lon < 180.0:
            for f, (x0, y0, x1, y1) in zip(feats, boxes):
                if x0 <= lon <= x1 and y0 <= lat <= y1 and \
                        feature_contains(lon, lat, f["geometry"]):
                    dots.append([round(lon, 1), round(lat, 1)])
                    break
            lon += STEP
        lat += STEP
    print("%d land dots at %.1f degrees" % (len(dots), STEP))

    payload = json.dumps(dots, separators=(",", ":"))
    block = "\n".join([
        START,
        '  <script type="application/json" id="cp-globe-dots">%s</script>' % payload,
        END,
    ])

    s = io.open(PAGE, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in s else "\n"
    block = block.replace("\n", nl)
    if START in s:
        a = s.index(START)
        b = s.index(END) + len(END)
        s = s[:a] + block + s[b:]
    else:
        raise SystemExit("markers not found; add them to index.html first")
    io.open(PAGE, "w", encoding="utf-8", newline="").write(s)
    print("written: %d bytes of coordinates" % len(payload))


if __name__ == "__main__":
    main()
